simd-everywhere/simde

simde/x86/sse4.1.h

Explicitly casting to __m128* on this line appears to be necessary to compile using clang or gcc when SIMDE_SSE4_1_NATIVE is defined.

sse4.1: Add missing explicit cast to __m128i*

---

.travis.yml
test/CMakeLists.txt

And make arm32 mandatory to pass, now that it does

include libstdc++.so.6 for armhf

---

simde/x86/sse2.h

Error showed up while using -DSIMDE_ENABLE_NATIVE_ALIASES .

Add missing parenthesis in _mm_bsrli_si128 and _mm_srli_si128 defines.

---

.editorconfig

https://editorconfig.org/
Related to #93 
We could also add a shortcut using a tool that people could run locally or as part of a git submit hook
Options for that local reformatting include:
1. `astyle -s2 $(find test simde -type f -name '*[ch]')` (also makes the brace style consistent, see http://astyle.sourceforge.net/astyle.html#_Basic_Brace_Styles for more options)
2. [`uncrustify`](https://github.com/uncrustify/uncrustify) So many options!
3. [`indent`](https://www.gnu.org/software/indent/)
4. ['clang-format'](http://clang.llvm.org/docs/ClangFormat.html)

Create .editorconfig to document coding standard

---

.drone.yml

This PR is to add Fedora rawhide aarch64 (arm64) clang (10.0.0) case to Drone CI.
As the rawhide is a development environment, while it's good to check it on the latest compilers, it might be good to build with `failure: ignore`.
And it reproduces https://github.com/nemequ/simde/issues/167 .

suggestion: drone: add Fedora rawhide clang build.

---

simde/x86/avx2.h
simde/x86/sse2.h
test/docker/Dockerfile.ppc64el
test/native-aliases.sh

I had to make a pull request because `remote: error: Required status check "nemequ.simde" is expected.`

ppc64le: add missing conversions to simde__m* return types

---

.travis.yml
docker/Dockerfile

Previous packages were beta. This is the first product release of oneapi and the team has promised not to change the package names anymore.

update icc package name for oneapi gold release

---

.github/workflows/ci.yml
simde/x86/avx.h
simde/x86/avx2.h

Remove useless for-loops
Remove redundant to_private/from_private
Remove redundant defined(SIMDE_ARM_NEON_A32V7_NATIVE) when we already check for SIMDE_NATURAL_VECTOR_SIZE_LE(128)

x86/avx{2,}.h: Normalize SIMDE_NATURAL_VECTOR_SIZE

---

simde/x86/avx512/permutex2var.h
test/x86/avx512/permutex2var.c

Add `_mm{,256}_{,mask_,mask2_,maskz_}permutex2var_epi{8,16,32,64}` intrinsics to permutex2var.[ch]
Add `_mm{,256}_{,mask_,mask2_,maskz_}permutex2var_{pd,ps}` intrinsics to permutex2var.[ch]
Add AVX, SSE, NEON, Altivec and Wasm translations for most intrinsics.

avx512/permutex2var: add remaining intrinsics and translations

---

amalgamate.py

To update the amalgamated SIMDe header included in Emscripten, we run a wrapper
script around amalgamate.py. Since this wrapper script is typically run from the
Emscripten directory, the git id picked up by amalgamate.py was Emscripten's git
id rather than SIMDe's git id as intended. This PR changes the working directory
of the git command run by amalgamate.py so that it correctly reads SIMDe's git
id even when run from a different git repo.

Fix git_id when amalgamating from another git repo

---

simde/arm/neon/ld1_dup.h
simde/arm/neon/st2_lane.h
simde/arm/neon/st3_lane.h
simde/arm/neon/st4_lane.h
test/arm/neon/ld1_dup.c
test/arm/neon/st2_lane.c
test/arm/neon/st3_lane.c
test/arm/neon/st4_lane.c

This PR completes the following function families (WIP) :
- qrshrn_n
- qshlu_n
- qshrn_n
- rsra_n
- shl
- shl_n
- sri_n

Neon: Implement incomplete function families pt. 2

---

simde/arm/neon/cvt.h
simde/arm/neon/qadd.h
simde/arm/neon/qsub.h

Fix warnings with -fno-lax-vector-conversions

---

.github/workflows/ci.yml
test/check-flags.sh

This pull request recombines the x86 tests and passes the `-future` flag to Intel SDE, which should provide support for current and future architecture extensions.
According to the previous SDE error message, it was defaulting to the host's CPUID because no flag had been set. If the host machine did not support a particular architecture, the test would fail. 
Here is the list of flags from running `./sde64 --help` that could be used instead for a particular processor microarchitecture:
```
-quark              Set chip-check and CPUID for Intel(R) Quark CPU
-p4                 Set chip-check and CPUID for Intel(R) Pentium4 CPU
-p4p                Set chip-check and CPUID for Intel(R) Pentium4 Prescott CPU
-mrm                Set chip-check and CPUID for Intel(R) Merom CPU
-pnr …
```

CI Fixes: SDE fix

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy.yml
.github/workflows/msvc-arm.yml
.github/workflows/ossar-analysis.yml

This pull request addresses CI warnings about deprecated, or soon to be unsupported build tools: 
- `actions/checkout` is updated to v3 to use Node 16
- The macos build is set to macOS version 11
- The 18.04 gcc and clang builds are commented out
- `codecov/codecov-action` is set to v3
I was able to verify all but the codecov changes on my fork. According to the [codecov readme](https://github.com/codecov/codecov-action/blob/main/README.md), there may be some breaking changes between the two versions.

CI Fixes: Address CI warnings

---

test/test.h
test/wasm/simd128/demote.c
test/wasm/simd128/floor.c
test/wasm/simd128/max.c
test/wasm/simd128/min.c
test/wasm/simd128/pmax.c
test/wasm/simd128/pmin.c
test/wasm/simd128/trunc.c

Hi, thank you for SIMDe! I'm working on wasm2c and trying to get the full Wasm testsuite passing when using SIMDe as backend for the Wasm simd128 operations. We're seeing a small number of differences from the Wasm-specified behavior (https://github.com/WebAssembly/wabt/pull/2021#issuecomment-1396386135), most involving either negative zero or NaNs.
As a first step, here is a PR that cranks up the strictness of the Wasm tests for demote, floor, max, min, ~nearest,~ pmax, pmin, and trunc. Currently these are tested to within the nearest 0.1; this PR would change that to an exact comparison (which I think is acceptable even in a fast-math situation as these are basically all selectors or integer truncation?). This also changes the overall test.h to do an exact bitwise comparison when …

Test some Wasm instructions more strictly

---

.packit.yml
.packit/README.md
.packit/ci.sh
.packit/simde.spec

This PR fixes https://github.com/simd-everywhere/simde/issues/1036.
In my investigation, [Packit CI](https://packit.dev/docs/guide/) is the best to test SIMDe in Fedora rawhide cases.
Pros:
* Test with Fedora project's native CPU environments, x86_64, i686, aarch64, ppc64le and s390x.
* No limits or very long time limits for running time. I checked at least possible to run a job for 1 hour 57 minutes.
* The internally used infra ([Fedora COPR](https://copr.fedorainfracloud.org/coprs/)) is also used in Fedora project. We can expect a level of stability and longevity.
Cons:
* In my impression, very early stage of the product. However, I see even popular open source projects such as [Podman](https://github.com/containers/podman) using it. It can be polished. The CI sometimes doesn't have …

Add Packit CI.

---

.packit.yml
.packit/README.md
.packit/simde.spec

This PR has 2 commits.
* Packit: Refactoring: Remove a duplicated command to unset LDFLAGS.
I found a small issue.
* Packit: Add a document of why we want to keep Fedora rawhide in CI.
I added a note about the topic mentioned at https://github.com/simd-everywhere/simde/issues/1036#issuecomment-1573502939.

Packit: Update a document of why and refactoring

---

simde/x86/avx512/gather.h
test/x86/avx512/gather.c

Split out from https://github.com/simd-everywhere/simde/pull/1029
https://github.com/simd-everywhere/simde/actions/runs/5220929545/jobs/9424594581#step:10:817

avx512/gather: mm512_{mask_,}i64gather_{epi32,epi64,ps,pd)

---

.packit.yml
.packit/ci.sh

Added the i386 (machine cpu: i686) case to the Packit CI. The CI only runs 1 test (GCC O2 flag test) in the i386 case, because the case takes longer running time than other CPU cases, and fails in the GCC default test.
I tested by running Packit CI 2 times in my forked repository. Interestingly the running times are shorter than my test yesterday. Now we can manage the executed tests for each CPU case.
* https://copr.fedorainfracloud.org/coprs/packit/junaruga-simde-wip-ci-packit-skip-cpu/build/6061404/
* https://copr.fedorainfracloud.org/coprs/packit/junaruga-simde-wip-ci-packit-skip-cpu/build/6061407/
I checked that only one test was executed in the i686 case, and 2 tests were executed as before in other CPU cases.
x86_64
```
== Results ==
Exit status: 0
ok gcc without flags
ok gcc with …
```

Packit: Add a feature to skip specific tests in the specific CPU cases.

---

.github/workflows/ci.yml
simde/simde-arch.h
simde/simde-f16.h

The `_Float64`  support under clang for RISCv64 is not working :-(

RISCV64 & clang

---

.packit/simde.spec
README.md

This PR has 2 commits below for refactoring. The CI result on my forked repository is [here](https://copr.fedorainfracloud.org/coprs/packit/junaruga-simde-wip-ci-packet-refactoring/build/6096104/).
* Add Packit CI to the README. The updated README is [here](https://github.com/junaruga/simde/blob/wip/ci-packet-refactoring/README.md).
Note that the linked page is a common history page including other open source projects. It seems the CI doesn't have the project specific history page.
* Packit: Unset unused environment variables in a simpler way.
I found the way[1].
* [1] https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/macros#_101
> Automatically use set_build_flags macro for build, check, and
> install phases.
> Use "%undefine _auto_set_build_flags" to disable"

Packit: Refactoring: Unset unused environment variables in a simpler way, and update the README.

---

.packit/README.md

I noticed a small typo. We need to escape the special character "*" to print it.
[Here](https://github.com/junaruga/simde/blob/wip/ci-packit-readme/.packit/README.md) is the modified README.

Packit: README: Fix typo.

---

simde/simde-arch.h

when using `/arch=AVX` or similar then SSE4.2 does not get activated (on MSVC at least, but should be similar on g++/clang)
This PR fixes this.

fix SIMDE_ARCH_X86_SSE4_2 define

---

.packit/ci.sh

This fixes the following issue found at https://github.com/simd-everywhere/simde/pull/1055#issuecomment-1683738127.
```
+ pip3 install meson==0.55.0
...
Installing collected packages: meson
WARNING: The script meson is installed in '/builddir/.local/bin' which is not on PATH.
...
+ meson setup build/gcc
/builddir/build/SOURCES/ci.sh: line 15: meson: command not found
...
```

Packit: Set PATH for commands installed by `pip install`.

---

simde/arm/neon/min.h

This removes non-working MMX specialization from function simde_vmin_s16, described in #1063.

Remove non-working MMX specialization from simde_vmin_s16

---

simde/arm/neon/shll_n.h
simde/simde-common.h
test/arm/neon/shll_n.c

This extends constant range in simde_vshll_n_XXX intrinsics according to #1064, including tests for new values.

Extend constant range in simde_vshll_n_XXX intrinsics

---

simde/x86/avx.h
test/x86/avx.c

- add test from #926
- avx: simde_mm256_shuffle_pd fix for natural vector size < 128
Fixes: #926

avx: fix _mm256_shuffle_pd impl

---

simde/x86/avx.h
simde/x86/avx2.h
simde/x86/sse.h
simde/x86/sse2.h
simde/x86/sse4.1.h

- sse{,2,4.1}, avx{,2} `*_stream_{,load}*`: use `__builtin_nontemporal_{load,store}`
- sse `_mm_movemask_ps`: remove unused code
Fixes: https://github.com/simd-everywhere/simde/issues/938

Use clang's nontemporal builtins, if available

---

.github/workflows/ci.yml

This reverts commit 07eb419093e952fd48d8486a3b5a8e366ba5b055 now that https://github.com/emscripten-core/emscripten/issues/20250 is fixed.
Blocked by

gh-actions: emscripten switch to "tip of tree"

---

.appveyor.yml
simde/simde-f16.h
simde/simde-features.h

- appveyor: save meson log on error
- appveyor: preserve test log
- fp16: don't use _Float16 on ClangCL if not supported
- svml: don't enable SIMDE_X86_SVML_NATIVE for ClangCl

ClangCl fixes

---

.packit/README.md

This PR is to improve Packit CI document adding troubleshooting section in the `README.md`. The Copr outage issue at https://github.com/simd-everywhere/simde/pull/1108#issuecomment-1807591166 made me send this PR.
You can check the modified README [here](https://github.com/junaruga/simde/blob/wip/ci-packit-readme-troubleshooting/.packit/README.md) in my forked repository.
I also updated the markdown format, referring to citations. I learnt the style on [Sway window manager's README](https://github.com/swaywm/sway/blob/master/README.md?plain=1).

Packit CI: Add troubleshooting section in README. [ci skip]

---

simde/simde-common.h
simde/x86/avx512/abs.h

Fix check for gcc bug in abs.h .
The gcc bug is described here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87467
It is fixed in versions 7.4.0 and 8.3.0 and above.

avx512 abs: refine GCC compiler checks for `_mm512{,_mask}_abs_pd`

---

simde/x86/avx2.h
test/x86/avx2.c

Hi,
There is an error in the implementation of simde_mm256_sign_epi16(). The implementation does not handle the "==0" case of the avx2 intrinsic. I didn't understand the entire test workflow but i would guess that the error is not detected because the test vector in test_simde_mm256_sign_epi16() doesn't contain any 0s.
Feel free to edit the pull request/code.
This is the Pseudo code of the _mm256_sign_epi16 intrinsic from the Intel Intrinsics guide:
```
FOR j := 0 to 15
i := j*16
IF b[i+15:i] < 0
dst[i+15:i] := -(a[i+15:i])
ELSE IF b[i+15:i] == 0
dst[i+15:i] := 0
ELSE
dst[i+15:i] := a[i+15:i]
FI
ENDFOR
dst[MAX:256] := 0
```

correction of simde_mm256_sign_epi16().

---

simde/arm/neon/sqadd.h
simde/arm/neon/uqadd.h

The arm_neo.h bug of msvc is fixed. So that the workaround is not needed on new msvc

apply arm64 windows workaround only on older version msvc

---

simde/x86/avx512/add.h

Improve and simplify implementation of `simde_mm512_add_epi32` as follows:
1. Remove the explicit SVE implementation. For SVE vector lengths of VL={128, 256}, this explicit vector length agnostic (VLA) SVE loop performs significantly worse than the Neon equivalent, which can be executed using fewer instructions. This sequence of SVE intrinsics is also malformed according to clang, so it fails to compile altogether.
2. Preferentially use GCC's vector extension if available, instead of repeated calls to `simde_mm256_add_epi32`. There are a couple of reasons for this:
1. The added indirection results in worse code generation. See the code generation attached to commit message for an example with GCC 13.
2. GCC's vector extension is an easier optimization target for compilers, allowing them …

Improve performance of simde_mm512_add_epi32

---

simde/simde-detect-clang.h

https://releases.llvm.org/13.0.0/tools/clang/docs/DiagnosticsReference.html#waix-compat
seems to have been incorrectly written in 7bc774fc7087748b8abf2bd6586d2d87df72fe8b
verified working as expected for clang 13 with godbolt: https://godbolt.org/z/cr1YhKv6b

Update simde-detect-clang.h for clang 13 detection

---

simde/simde-detect-clang.h

Verified with godbolt:
- when using clang 17, it's 170000: https://godbolt.org/z/MTzb8va48
- when using clang 16, it's 160000: https://godbolt.org/z/8avxvq7rj

Update simde-detect-clang.h for clang 17 detection

---

.dockerignore
.github/workflows/ci.yml

- docker: ignore common build paths
- gh-actions emscripten: use older release while we wait for https://github.com/emscripten-core/emscripten/issues/21368

GitHub Actions emscripten: use older release for now

---

.packit.yml
.packit/ci.sh

We don't maintain the i386 (i686) case on Packit CI any more due to a limitation of the human power.
Note that the i386 (i686) case is a kind of deprecated state in Fedora project. See the following links for details.
* https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval
* https://fedoramagazine.org/in-fedora-31-32-bit-i686-is-86ed/

Packit: Drop i386 (i686) support.

---

.packit/simde.spec
README.md
docker/README.md
simde/simde-align.h
simde/simde-complex.h
simde/simde-diagnostic.h
simde/simde-f16.h
simde/x86/avx512/xorsign.h
simde/x86/sse.h
test/x86/f16c.c

Per https://github.com/simd-everywhere/simde/pull/1152#issuecomment-2021047051
Should the following two architectures also be added?
- ARMv8 SVE - it's in [simde-features.h](https://github.com/simd-everywhere/simde/blob/b88a66de3a7de7a16099ab28019bc566e4468b82/simde/simde-features.h), but I couldn't find it in ci.yml
- z/Architecture **ZVECTOR** - it's in simde-features.h, but ci.yml just lists s390x, so unclear if ZVECTOR extensions are utilized

README.md - move CLMUL to partial, list more of the CI.yml architectures

---

simde/arm/neon/ld2_lane.h
simde/arm/neon/ld3.h
simde/arm/neon/ld3_lane.h
simde/arm/neon/ld4.h
simde/arm/neon/st3.h
simde/arm/neon/st4.h
simde/arm/neon/types.h

Hi, I run the arm-neon-tests (https://github.com/christophe-lyon/arm-neon-tests) for simde neon2rvv, and have set the flags `-DSIMDE_RISCV_V_NATIVE -DSIMDE_ARM_NEON_A32V7_ENABLE_NATIVE_ALIASES` to compiler. But I get some compiler reported errors as follow, it means that vld4_s6 is not supported  in simde neon2rvv.
```
ref_vldX.c:200:3: error: call to undeclared function 'vld4_s64'; ISO C99 and later do not support implicit function declarations 
```
As I know，vld4_s64 and the other intrinsic function which are mentioned in my patch are supported in armv7 platform.  But simde disable them in armv7 platform.  So I upload the patch to enable those intrinsic function in armv7 platform. Please help to review, thanks.

arm: enable more intrinsic function for armv7

---

simde/arm/neon/qdmlal.h
simde/arm/neon/qdmlsl.h
simde/arm/neon/qrdmulh.h
simde/arm/neon/qrshl.h
simde/arm/neon/rshl.h
test/arm/neon/qdmlal.c
test/arm/neon/qdmlsl.c
test/arm/neon/qrdmulh.c
test/arm/neon/qrdmulh_n.c
test/arm/neon/qrshl.c
test/arm/neon/rshl.c

1. For vqdmlal_s16/s32, the doubling result maybe overflow, so need to use vqaddq_s16/32 to saturate it. As the same with vqdmlsl_s16/32.
2. The vrdmulh family function need to use vqadd saturating function to avoid the doubling result overflow. But now I just use rvv intrinsic function to replace the RISCV_V_NATIVE implementation.
3. The result of vrshl family function need to keep the sign bit of the origin data. If` a > 0 && b < 0,` the result of `(a + (1 << (-b - 1)))` maybe overflow into a negative value. And in gcc/clang, >> means the arithmetic shift left, so it will get the incorrect sign bit whithout unsigned extend value.

arm: fix some neon2rvv intrinsic function error

---

simde/arm/neon/maxnm.h
simde/arm/neon/minnm.h
simde/simde-features.h

WebKit project recently imported simde 0.8.2
Since then the build for Aarch64 targeting RPi4 boards has started giving lot of warnings related to the simde header:
`  warning: "__ARM_NEON_FP" is not defined, evaluates to 0 [-Wundef]`
Add a check to ensure that `__ARM_NEON_FP` is defined.
Related: https://bugs.webkit.org/show_bug.cgi?id=273789

neon: avoid warnings when "__ARM_NEON_FP" is not defined.

---

simde/x86/sse4.2.h

Apply half tabular method in `_mm_crc32` family

x86: Apply half tabular method in `_mm_crc32` family

---

simde/simde-f16.h

_Float16 is only supported on a few architectures. Let's assume it's not supported unless we know otherwise.
References:
* https://bugs.webkit.org/show_bug.cgi?id=274086
* https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html
* https://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point

Don't use _Float16 on architectures that do not support it

---

simde/x86/sse2.h

This PR removes a duplicated translation for WASM for the SSE2 `_mm_add_pd` intrinsic.

x86: remove redundant _mm_add_pd translation for WASM

---

simde/x86/fma.h

When building x86_64 intrinsics for arm64 (armv8.2) using gcc 10 and 11 with -O2, we observed poor performance in some math functions. One of the reasons turned out to be how `_mm256_fnmadd_pd` was being compiled. I made a simple test case for further evaluation:
```cpp
void fma_test(__m256d a, __m256d b, __m256d c, __m256d* d) { *d = _mm256_fnmadd_pd(a, b, c); }
```
With our default settings `-O2 -march=armv8.2-a` on gcc 10, this compiled to the following:
```
0000000000000000 <fma_test(double __vector(4), double __vector(4), double __vector(4), double __vector(4)*)>:
0:   d102c3ff        sub     sp, sp, #0xb0
4:   aa0103e6        mov     x6, x1
8:   9100ffe5        add     x5, sp, #0x3f
c:   d2800024        mov     x4, #0x1                        // #1
10:   927be8a5        and     x5, …
```

Use 128 bit fnmadd_pd to do 256 bit fnmadd_pd

---

simde/x86/sse.h
simde/x86/sse2.h

Preprocessor checks should probably be substituted with SIMDE_* alternatives, but I'm not very familiar with these, so it could use a review. #1193

Substitution for MemoryBarrier() to avoid including <windows.h>

---

simde/x86/sse2.h

Implements `_mm_sad_epu8` using Wasm SIMD intrinsics. 
Props to @Maratyszcza for showing this approach in Emscripten: https://github.com/emscripten-core/emscripten/pull/12416 .

x86 wasm: Wasm SIMD version of `_mm_sad_epu8`

---

simde/wasm/simd128.h

This PR provides WASM to NEON translations from `wasm_u16x8_avgr` to `vrhaddq_u16` and `wasm_u8x16_avgr` to `vrhaddq_u8`. 
I also tested these locally on a Mac Mini M1. 
Something worth noting here is that the AltiVec translation may also work, but I haven't tested it on a physical device.
Here is what that change looks like: https://github.com/wrv/simde/commit/ff4e85ac47e538aff820514ff728ca3fa6382a9a
And the GH Actions result on that change: https://github.com/wrv/simde/actions/runs/10461140123  
If that looks alright, I can add it to this PR.

wasm NEON and AltiVec: add u16x8 and u8x16 avgr translations

---

simde/arm/neon/st4.h

This PR translates `vst4_u8` to Wasm SIMD. We change the header to match the Arm `vmovl` Wasm translations: https://github.com/simd-everywhere/simde/blob/master/simde/arm/neon/movl.h#L43 .

arm wasm: add `vst4_u8` translation to Wasm SIMD

---

simde/arm/neon/shll_n.h

This PR adds Wasm SIMD translations for Arm `vshll_n_*` instructions.

arm wasm: add vshll translations to Wasm SIMD

---

simde/arm/neon/st2.h

This PR adds a translation from `vst2_u8` to Wasm SIMD using the similar approach as https://github.com/simd-everywhere/simde/pull/1209.

arm wasm: add `vst2_u8` translation to Wasm SIMD

---

.github/workflows/ci.yml
docker/cross-files/loongarch64-gcc-14-ccache.cross
simde/x86/sse.h

When compile webkitgtk-2.45.92, failed with following error:
webkitgtk-2.45.92/Source/WTF/wtf/simde/arm/neon.h:92893:38: 错误：cannot convert ‘__m128’ to ‘v2i64’ in assignment
92893 |         r_.lsx_i64 = __lsx_vfrintrm_s(a_.lsx_f32);
|                      ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
|                                      |
|                                      __m128

x86/sse: Fix type convert error for LSX.

---

simde/x86/avx.h

Simple test case:
```cpp
void test(double* dst, double* a) {
__m256d b = _mm256_loadu_pd(a);
__m256d c = _mm256_add_pd(b, b);
_mm256_storeu_pd(dst, c);
}
```
On arm64, with gcc 11 (`-O2 -fno-stack-protector -march=armv8.2-a`) it generates the following:
```
0000000000000000 <_Z4testPdS_>:
0:   ad400021        ldp     q1, q0, [x1]
4:   d10143ff        sub     sp, sp, #0x50
8:   9100ffe2        add     x2, sp, #0x3f
c:   927be842        and     x2, x2, #0xffffffffffffffe0
10:   4e61d421        fadd    v1.2d, v1.2d, v1.2d
14:   4e60d400        fadd    v0.2d, v0.2d, v0.2d
18:   ad000041        stp     q1, q0, [x2]
1c:   ad400440        ldp     q0, q1, [x2]
20:   ad000400        stp     q0, q1, [x0]
24:   910143ff        add     sp, sp, #0x50
28:   d65f03c0        ret
```
Note the confusing …

_mm256_storeu_pd and _mm256_loadu_pd using 128 bit lanes

---

simde/x86/avx.h
simde/x86/avx512/cmp.h
simde/x86/sse.h

Closes: https://github.com/simd-everywhere/simde/issues/1219
@Remnant44 I think there are more that could be converted. If you want to send a follow up PR for the other functions, using this as a guide, please do so.

x86: better implementations for MSVC and others without SIMDE_STATEMENT_EXPR_

---

.github/workflows/ci.yml
docker/cross-files/loongarch64-clang-18-ccache.cross
docker/cross-files/riscv64+rvv_vlen128_elen64-clang-17-ccache.cross
docker/cross-files/riscv64+rvv_vlen128_elen64-clang-18-ccache.cross
docker/cross-files/riscv64+rvv_vlen128_elen64_zvfh-clang-17-ccache.cross
docker/cross-files/riscv64+rvv_vlen128_elen64_zvfh-clang-18-ccache.cross
docker/cross-files/riscv64+rvv_vlen256_elen64-clang-17-ccache.cross
docker/cross-files/riscv64+rvv_vlen256_elen64-clang-18-ccache.cross
docker/cross-files/riscv64+rvv_vlen256_elen64_zvfh-clang-17-ccache.cross
docker/cross-files/riscv64+rvv_vlen256_elen64_zvfh-clang-18-ccache.cross
docker/cross-files/riscv64+rvv_vlen512_elen64-clang-17-ccache.cross
docker/cross-files/riscv64+rvv_vlen512_elen64-clang-18-ccache.cross
docker/cross-files/riscv64+rvv_vlen512_elen64_zvfh-clang-17-ccache.cross
docker/cross-files/riscv64+rvv_vlen512_elen64_zvfh-clang-18-ccache.cross
simde/simde-f16.h

Fixed the compilation issue on the Loongarch platform with clang:
` ../test/x86/avx512/../../../simde/simde-f16.h:100:11: error: _Float16 is not supported on this target.`

loongarch float16: use a portable version to avoid compilation errors

---

simde/x86/avx512/types.h

Clang has a `typedef unsigned long long __mask64` defined in `avx512bwintrin.h` ([link](https://clang.llvm.org/doxygen/avx512bwintrin_8h.html#a910ccf7d2141c4a3b8675e2480cc33ff)) and  causes `typedef redefinition with different types ('uint64_t' (aka 'unsigned long') vs 'unsigned long long')` error. 
This PR adds clang case in to the logic to fix this error.
See this for more detail: https://github.com/simd-everywhere/simde/commit/e8390a3bfb3bd9e5119a9883fb29b07169b2fe4d#r149134782

Fix clang type redef error

---

simde/arm/neon/sha256.h
simde/arm/neon/sha512.h
simde/arm/neon/sm3.h
simde/arm/neon/sm4.h
simde/x86/sse2.h

Most SIMDe functions/macros/etc have the SIMDE_ or simde_ prefix internally. Several of the ARM hash functions do not have this prefix on their ROR/ROL/LSR/LSL macros, and this means that the standard names of can conflict with other projects using the library.  This was an issue on an internal tool using the library, and while SIMDe undefines the macros after the file uses them, this is not compatible with other declarations of these macros before the SIMDe library is included.
This is purely a cosmetic change with internal function renaming.  It changes no external interfaces, simply removes a source of potential conflict with other projects that have similarly named macros.  Tests have not been changed, as there are no changes that would require test modification.

arm: Rename internal ARM ROL/ROR/LSR/LSL functions with a SIMDE prefix.

---

simde/arm/neon/qdmull.h
test/arm/neon/qdmull.c

The non-vectorized SQDMULL implementation was wrong for 32-bit inputs.  It incorrectly checked one of the operands to see if the value would overflow before doubling it, not the result of the initial multiplication.  It now matches the 16-bit operand version in flow (which was correct), and also matches hardware.  A test has been added for the scalar form of the function, testing a range of values that will saturate when multiplied and doubled.  This set of test vectors was produced on an ARMv9 machine (Google Cloud box), failed tests on x86 with the existing code, and passes with the modified code.
I have not tested the vectorized versions of this with WASM and RISC-V to see if they're correct, only the fallback code.

Fix SQDMULL implementation for 32-bit inputs.

---

simde/arm/neon/qdmlal.h
simde/arm/neon/qdmlal_high.h
simde/arm/neon/qdmlal_high_lane.h
simde/arm/neon/qdmlal_high_n.h
test/arm/neon/qdmlal.c
test/arm/neon/qdmlal_high.c
test/arm/neon/qdmlal_high_lane.c
test/arm/neon/qdmlal_high_n.c
test/arm/neon/qdmlal_lane.c
test/arm/neon/qdmlal_n.c

qdmlal instructions were implemented without saturation. This has been fixed by utilising existing SIMDe saturating mult and add instructions. Unit tests have been updated to test for all possible saturation cases.
- Fix qdmlal, qdmlal_n, qdmlal_lane,  qdmlal_high, qdmlal_high_n and qdmlal_high_lane
- Update unit tests for qdmlal, qdmlal_n, qdmlal_lane, qdmlal_high, qdmlal_high_n, qdmala_high_lane

Fix qdmlal instructions

---

simde/arm/neon/qrdmulh.h
test/arm/neon/qrdmulh.c

The only reason the SSE code for qrdmulh passed is because the edge cases were not included in the tests unless SSE was disabled.  The `INT16_MIN * INT16_MIN` case ought result in `INT16_MAX` - and it does, in the fallback code.  It does not, in the SSE code, which is what will typically be used on x86 hardware.  Saturating code not handling edge cases is simply wrong.
Unfortunately, my SSE skills are not sufficient to sort out how to fix this problem.  I'd also be fine commenting out the code with a note about the problem, but I prefer correct results in all cases to "commonly correct results except in the case where the result matters."
Tests are modified to remove the conditional test.  The final test cases passes cleanly on ARMv9 hardware, but not on x86 with SSE.  It passes in the …

Remove incorrect qrdmulh SSE code.

---

simde/x86/avx2.h
simde/x86/sse2.h

Happy New Year, Michael @mr-c. 
We rewrited the PR https://github.com/simd-everywhere/simde/pull/1247 (can be closed now) and seperated it into two patches. We did two things on them.
1）The first thing is to fix a typo for lasx implemention in x86 avx2 that modified simde_mm256_bslli_epi128 to simde_mm256_bsrli_epi128, very sorry for this typo error.
2）The second thing is to work around compiler errors in use-cases that users would pass variables for shift count for slli/srli/srai instrutions, which can not support for loongarch at present.
We hope you could take some time to review this for us, if you have any questions please feel free to let us know, thank you Michael， thank you.

Fixes for loongarch compilers

---

.github/workflows/ci.yml
simde/x86/sse2.h
simde/x86/sse3.h
test/x86/avx.c

- x86 sse2,sse3, avx: silence some false-positive warnings about unitialized structs
- gh-actions: x86 upgrade to GCC-14

silence some warnings

---

simde/simde-arch.h

Enable RVV when there are zve64d and zvl128b flags.

[Neon][RVV] Enable RVV when there are zve64d and zvl128b flags.

---

simde/arm/neon/ld2.h
simde/arm/neon/ld3.h
simde/arm/neon/ld4.h
simde/arm/neon/st2.h
simde/arm/neon/st3.h
simde/arm/neon/st4.h
simde/simde-arch.h

Enable RVV segment load/store only when we have __riscv_zvlsseg flag.

[Neon][RVV] Enable RVV segment load/store only when we have __riscv_zvlsseg flag.

---

simde/simde-common.h
simde/simde-features.h

Fallback to auto vectorization if there is no mvv-vector-bits flag.

[Neon][RVV] Fallback to autovec without mrvv-vector-bits flag.

---

simde/x86/sse2.h

It seems there is some problem for GCC in dealing with vector type on Ternary Operator, see below:
```
//test.c
#define SIMDE_ENABLE_NATIVE_ALIASES
#include "/home/jin/data/community/simde-loong64/simde/x86/sse2.h"
int main()
{
__m128i a = {8};
__m128i b = _mm_slli_si128(a, 3);
return 0;
}
```
gcc -mlsx test.c，the compile output is:
```
In file included from test.c:2:
test.c: In function ‘main’:
/home/jin/data/community/simde-loong64/simde/x86/sse2.h:1347:22: error: type mismatch in conditional expression
(((imm8)<=0) ? (a) : (((imm8)>15) ? simde_mm_setzero_si128() : simde__m128i_from_lsx_i8((v16i8)__lsx_vbsll_v(simde__m128i_to_private(a).lsx_i64, (imm8)))))
^
/home/jin/data/community/simde-loong64/simde/x86/sse2.h:1406:35: note: in expansion of macro ‘simde_mm_bslli_si128’
#define …
```

x86 sse2 for loongarch: fix GCC build failure

---

simde/arm/neon/mul_lane.h

This is the minimal patch that makes tests pass with clang 20.1.x on Fedora rawhide x86_64 and aarch64.
Fixes #1295 .

Avoid undefined behaviour with signed integer multiplication

---

simde/arm/neon/types.h
test/native-aliases.sh

Half-precision multi-vector types are available on the VFPv3_fp16 and VFPv4 architectures for ARMv7

Add NEON float16 multi-vectors to native aliases

---

.github/actionlint-matcher.json
.github/workflows/actionlint.yml
.github/workflows/ci.yml
simde/arm/neon/and.h
simde/arm/neon/cge.h
simde/arm/neon/mvn.h
simde/x86/sse.h
simde/x86/sse2.h
simde/x86/sse4.1.h
simde/x86/svml.h

Misuse RVV intrinsics vnot. We didn't find this error cause it always use builtin vector operation in the testing.

prefer NATIVE implementations over SIMDE_VECTOR_SUBSCRIPT_OPS, remove some broken optimized implementations

---

simde/x86/avx512/srli.h
test/x86/avx512/srli.c

partially addresses https://github.com/simd-everywhere/simde/issues/104#issuecomment-3247758541

x86 avx512 srli: add mask{,z} varients

---

.circleci/config.yml
simde/simde-common.h

Fix the portable memory functions and test them in CI

---

test/test.h

Fixes this:
```
In file included from test/common/common.cpp:1:
../simde-b673cb2ec15a160ae34d8c002af5d550bd127375/test/common/../test.h: In function 'void simde_test_codegen_i8(size_t, char*, int8_t)':
../simde-b673cb2ec15a160ae34d8c002af5d550bd127375/test/common/../test.h:187:61: error: expected ')' before 'PRId8'
187 |     simde_test_codegen_snprintf_(buf, buf_len, "%cINT8_C(%4" PRId8 ")", (value < 0) ? '-' : ' ', HEDLEY_STATIC_CAST(int8_t, (value < 0) ? -value : value));
|                                 ~                           ^~~~~~
|                                                             )
../simde-b673cb2ec15a160ae34d8c002af5d550bd127375/test/common/../test.h:14:1: note: 'PRId8' is defined in header '<cinttypes>'; this is probably fixable by adding '#include <cinttypes>' …
```

test.h: define __STDC_FORMAT_MACROS if not defined

---

simde/arm/neon/ld1.h
simde/arm/neon/ld1q_x2.h
simde/arm/neon/ld1q_x3.h
simde/arm/neon/ld1q_x4.h
simde/arm/neon/types.h

- Consolidate and propogate the use of these speedups to all `vld1q_*_x[234]` functions
- Speedups for SSE3+ confirmed with the libjpeg-turbo benchmarks
- Entropy encoding went from 309 to 883 Mcoefficients/sec on GCC 12.2

arm neon `ld1{,q_x[234]}`: speedups on SSE[32] & WASM
