simde/x86/sse.h
=> Cope with unsupported rounding modes 

simde/x86/sse.h
added WASM implementation for mm_sub_ps and mm_mul_ps
=> Added WASM implementation for mm_sub_ps and mm_mul_ps

simde/x86/avx512f.h
avx512f.h: Correct new C&P errors
=> Lots more C&P errors in avx512f.h

README.md
added gitter chat link to README.md
=> added gitter chat link to README.md

simde/x86/avx2.h, test/x86/avx2.c
=> add missing test for _mm256_permute2x128_si256

simde/x86/avx512f.h, test/x86/avx512f.c
avx512f: mm512_maskz_broadcastd_epi32, mm512_maskz_broadcastq_epi64
=> avx512f: mm512_maskz_broadcastd_epi32, mm512_maskz_broadcastq_epi64

simde/x86/avx512f.h, test/x86/avx512f.c
avx512f: added implementation for mm512_{,mask,maskz}_broadcastss_ps
=> avx512f: added implementation for mm512_{,mask,maskz}_broadcastss_ps

simde/x86/avx512f.h, test/x86/avx512f.c
avx512f: added implementation for mm512_{mask,maskz}_cvtepi64_epi{8,16}
=> avx512f: added implementation for mm512_{mask,maskz}_cvtepi64_epi{8,16}

simde/x86/avx512f.h
avx512f : added copyright info in avx512f.h
=> avx512f : added copyright info in avx512f.h

simde/x86/avx512f.h, test/x86/avx512f.c
avx512f: added mm512_{mask,maskz}_cvtepi{64_epi32,8_epi{32,64}}
=> avx512f: added mm512_{mask,maskz}_cvtepi{64_epi32,8_epi{32,64}}

.github/workflows/ci.yml, .travis.yml, docker/cross-files/emscripten.cross
This attempts to fix the Travis CI timeout issue, and fixes the emscripten build process.
=> Ci fixes: Travis and Emscripten

.travis.yml, README.md
=> restart testing with Travis CI

.circleci/config.yml, .github/workflows/ci.yml
3.1.46+ fails: https://github.com/emscripten-core/emscripten/issues/20250
=> gh-actions: emscripten use 3.1.45, not tot

.github/workflows/ci.yml, docker/cross-files/riscv64-gcc-12-O3-ccache.cross, simde/arm/neon/ld2.h
Todo: adjust the cache names for the new CI job
=> arm neon ld2: silence warnings at -O3 on gcc risc-v

.github/workflows/ci.yml, docker/cross-files/i686-gcc-14.cross, simde/arm/neon/abs.h
https://github.com/llvm/llvm-project/issues/82112#issuecomment-1956469212
and resume testing emscripten using the 'tip of tree' ("tot") builds.
Fixes #901 
Fixes #658
=> arm/neon abs: negating INT_MIN is undefined behavior

simde/arm/neon/mvn.h, simde/arm/neon/qadd.h
use risc-v vector instrinsic to implement vqadd_xx and vmvn_xxx.
=> arm: improve performance in vqadd and vmvn in risc-v

.github/workflows/ci.yml, docker/Dockerfile, docker/cross-files/aarch64-clang-18-ccache.cross, docker/cross-files/aarch64-gcc-13-ccache.cross, docker/cross-files/armel-clang-18-ccache.cross, docker/cross-files/armel-gcc-13-ccache.cross, docker/cross-files/armv7-clang-18-ccache.cross, docker/cross-files/armv7-gcc-13-ccache.cross, docker/cross-files/armv8-gcc-13-32bit-ccache.cross, docker/cross-files/mips64el-clang-18-ccache.cross, docker/cross-files/mips64el-gcc-13-ccache.cross, docker/cross-files/power9-gcc-13-ccache.cross, docker/cross-files/ppc64el-clang-18-ccache.cross, docker/cross-files/riscv64+rvv_vlen128_elen64-clang-17-ccache.cross, docker/cross-files/riscv64+rvv_vlen128_elen64-clang-18-ccache.cross, docker/cross-files/riscv64+rvv_vlen128_elen64_zvfh-clang-17-ccache.cross, docker/cross-files/riscv64+rvv_vlen128_elen64_zvfh-clang-18-ccache.cross, docker/cross-files/riscv64+rvv_vlen256_elen64-clang-17-ccache.cross, docker/cross-files/riscv64+rvv_vlen256_elen64-clang-18-ccache.cross, docker/cross-files/riscv64+rvv_vlen256_elen64_zvfh-clang-18-ccache.cross, docker/cross-files/riscv64+rvv_vlen512_elen64-clang-17-ccache.cross, docker/cross-files/riscv64+rvv_vlen512_elen64-clang-18-ccache.cross, docker/cross-files/riscv64+rvv_vlen512_elen64_zvfh-clang-17-ccache.cross, docker/cross-files/riscv64+rvv_vlen512_elen64_zvfh-clang-18-ccache.cross, docker/cross-files/riscv64-clang-18-ccache.cross, docker/cross-files/riscv64-gcc-13-O3-ccache.cross, docker/cross-files/riscv64-gcc-13-ccache.cross, docker/cross-files/s390x-clang-18-ccache.cross, docker/cross-files/s390x-gcc-13-ccache.cross
add some more -13 (x86-64) and -14 (arm64) testing
=> gh-actions: macos & ubuntu maintenance

simde/simde-f16.h, simde/x86/sse2.h
Added the lsx interface to this file.
=> loongarch: add lsx support for sse2.h

simde/arm/neon/max.h, simde/arm/neon/min.h
Add min.h and max.h RVV implementations.
=> [Neon][RVV] add min.h and max.h RVV implementations.

.github/workflows/ci.yml, simde/simde-common.h, simde/simde-detect-clang.h
- detect-clang: detect version 20
- gh-actions: test clang 19 & clang 20
=> gh-action: test on clang 19 & 20
